#!/bin/sh


tell() {
  printf "\033[0;33m|-- ${*}\033[0m\n"
  printf "\033[0;31m" 1>&2 ;
  $* || {
    printf "\033[0m"
  }
}

explain() {
  printf "\033[0;34m${1}\033[0m\n"
}


ignoreRC="README.md|.gitignore|install.sh|dotfilesManager"
dir=~/dotfiles

explain "Create symlink for dotfiles"
# change to the dotfiles directory
cd $dir

files=`find . -maxdepth 1 -type f | sed 's|./||' | egrep -v $ignoreRC`

# create symlinks from the homedir to any files in the ~/dotfiles directory specified
for file in $files; do
  if [ -f ~/.$file ]; then
    tell rm ~/.$file
  fi
  tell ln -s $dir/$file ~/.$file
done

# explain "Create symlink for files config"
  # [ -d ~/.config/ ] || mkdir ~/.config/
  # tell cp -f --recursive --symbolic-link $dir/config/* ~/.config

zsh && exit
